import { addDays, toDateKey } from './date'
import type { PublicItem, PublicTip } from './types'

export function createDemoItems(now = new Date()): PublicItem[] {
  const today = toDateKey(now)
  const tomorrow = toDateKey(addDays(now, 1))
  const thirdDay = toDateKey(addDays(now, 2))

  return [
    {
      id: 'demo-seoul-assembly-1',
      region_code: 'KR-11',
      region_name: '서울',
      kind: 'assembly',
      title: '시연: 6.3 지방선거 재선거 요구 집회',
      event_date: today,
      time_start: '11:00',
      time_end: '14:00',
      time_text: '11:00 ~ 14:00',
      place_name: '광화문광장 인근',
      route_text: '광화문광장 → 세종대로사거리',
      traffic_note: '재선거 요구 집회 시연 데이터',
      participants_text: '출처 확인 필요',
      source_url: 'https://www.spatic.go.kr/spatic/main/assem.do',
      source_title: '6.3 지방선거 재선거 요구 집회 시연',
      agency: '시연 데이터',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-seoul-event-1',
      region_code: 'KR-11',
      region_name: '서울',
      kind: 'assembly',
      title: '시연: 선관위 앞 재선거 촉구 집회',
      event_date: tomorrow,
      time_start: '09:00',
      time_end: '12:00',
      time_text: '09:00 ~ 12:00',
      place_name: '중앙선거관리위원회 관악청사 인근',
      route_text: '중앙선거관리위원회 관악청사',
      traffic_note: '근거 링크 확인 필요',
      participants_text: '제보 검토 중',
      source_url: 'https://www.spatic.go.kr/spatic/main/assem.do',
      source_title: '재선거 요구 집회 시연',
      agency: '시연 데이터',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-busan-traffic-1',
      region_code: 'KR-26',
      region_name: '부산',
      kind: 'assembly',
      title: '시연: 부산 6.3 지방선거 관련 재선거 요구 집회',
      event_date: today,
      time_text: '16:00 ~ 20:00',
      place_name: '부산역 광장',
      route_text: '부산역 광장',
      traffic_note: '언론·제보 근거 확인 필요',
      participants_text: '제보 필요',
      source_title: '6.3 재선거 요구 집회 시연',
      agency: '시연 데이터',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-gwangju-event-1',
      region_code: 'KR-29',
      region_name: '광주',
      kind: 'assembly',
      title: '시연: 6.3 재선거 요구 집회',
      event_date: thirdDay,
      time_text: '13:00 ~ 18:00',
      place_name: '금남로 인근',
      route_text: '금남로',
      traffic_note: '제보 검토 중',
      source_title: '재선거 요구 집회 시연',
      agency: '시연 데이터',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-daejeon-notice-1',
      region_code: 'KR-30',
      region_name: '대전',
      kind: 'notice',
      title: '시연: 둔산권역 집회 안내',
      event_date: tomorrow,
      time_text: '10:30 ~ 12:30',
      place_name: '시청역 인근',
      route_text: '시청역 → 보라매공원',
      traffic_note: '점심 시간대 보행 혼잡',
      source_title: '지역 공지',
      agency: '공개 원문',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-jeju-event-1',
      region_code: 'KR-50',
      region_name: '제주',
      kind: 'event',
      title: '시연: 제주시청 주변 행사',
      event_date: today,
      time_text: '15:00 ~ 17:00',
      place_name: '제주시청',
      route_text: '제주시청 → 중앙로',
      traffic_note: '주변 주차 혼잡',
      source_title: '지역 행사 공지',
      agency: '공개 원문',
      updated_at: new Date().toISOString(),
    },
  ]
}

export function createDemoTips(now = new Date()): PublicTip[] {
  return [
    {
      id: 'demo-tip-1',
      region_code: 'KR-11',
      item_id: 'demo-seoul-assembly-1',
      category: 'move',
      body: '시청역보다 광화문역 북쪽 출구가 비교적 여유로운 편입니다.',
      nickname: '현장 메모',
      created_at: now.toISOString(),
    },
    {
      id: 'demo-tip-2',
      region_code: 'KR-11',
      item_id: null,
      category: 'return_home',
      body: '행사 종료 직후에는 종각 방면 버스 정류장이 빨리 붐빌 수 있습니다.',
      nickname: '익명',
      created_at: now.toISOString(),
    },
    {
      id: 'demo-tip-3',
      region_code: 'KR-26',
      item_id: 'demo-busan-traffic-1',
      category: 'accessibility',
      body: '해운대역 엘리베이터 이용 대기 시간이 길어질 수 있어 시간을 넉넉히 잡는 편이 좋습니다.',
      nickname: '부산 이동',
      created_at: now.toISOString(),
    },
  ]
}
